version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: electroshop-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - electroshop-net

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/electroshop
    depends_on:
      - mongo
    networks:
      - electroshop-net

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - electroshop-net

volumes:
  mongo-data:

networks:
  electroshop-net:
    driver: bridge
